---
# tasks file for php7.1
- name: Original - PHP7.1 - Installation de Php7.1 et extensions
  apt:
    pkg:
    - php7.1
    - php7.1-cli
    - php7.1-fpm
    - php7.1-bcmath
    - php7.1-curl
    - php7.1-dba
    - php7.1-dom
    - php7.1-enchant
    - php7.1-fileinfo
    - php7.1-gd
    - php7.1-imagick
    - php7.1-imap
    - php7.1-intl
    - php7.1-json
    - php7.1-ldap
    - php7.1-mbstring
    - php7.1-mysqli
    - php7.1-mysql
    - php7.1-mysqlnd
    - php7.1-odbc
    - php7.1-opcache
    - php7.1-pdo
    - php7.1-pgsql
    - php7.1-phar
    - php7.1-posix
    - php7.1-pspell
    - php7.1-redis
    - php7.1-soap
    - php7.1-sodium
    - php7.1-sqlite3
    - php7.1-sysvmsg
    - php7.1-sysvsem
    - php7.1-sysvshm
    - php7.1-tidy
    - php7.1-xmlreader
    - php7.1-xmlrpc
    - php7.1-xmlwriter
    - php7.1-xsl
    - php7.1-zip

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^upload_max_filesize'
    line: 'upload_max_filesize = 32M'
    state: present

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^post_max_size'
    line: 'post_max_size = 48M'
    state: present

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^memory_limit'
    line: 'memory_limit = 256M'
    state: present

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^max_execution_time'
    line: 'max_execution_time = 600'
    state: present

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^max_input_vars'
    line: 'max_input_vars = 3000'
    state: present

- name: Original - PHP7.1 - Modification de /etc/php/7.1/fpm/php.ini (php.ini)
  lineinfile:
    path: /etc/php/7.1/fpm/php.ini
    regexp: '^max_input_time'
    line: 'max_input_time = 1000'
    state: present

- name: Original - PHP7.1 - Redémarrage de php7.1
  shell:
    cmd: /etc/init.d/php7.1-fpm restart

- name: Original - PHP7.1 - Activation des extensions
  shell: |
    phpenmod -v 7.1 pdo_mysql
    phpenmod -v 7.1 pdo_odbc
    phpenmod -v 7.1 pdo_pgsql
    phpenmod -v 7.1 pdo_sqlite

- name: Original - redémarrage de Nginx
  service:
    name: nginx
    state: restarted